/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AutoBattler;

/**
 *
 * @author dbm3
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1magicGroup = new javax.swing.ButtonGroup();
        player2magicGroup = new javax.swing.ButtonGroup();
        player3magicGroup = new javax.swing.ButtonGroup();
        player4magicGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        Walking = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        leftrightTickbox = new javax.swing.JCheckBox();
        updownTickbox = new javax.swing.JCheckBox();
        lrstepsRoller = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        udstepsRoller = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        walkingcycleRoller = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        Battle = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Luneth = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        player1clevelTickbox = new javax.swing.JCheckBox();
        player1jlevelTickbox = new javax.swing.JCheckBox();
        player1Action = new javax.swing.JComboBox<>();
        player1customjobTickbox = new javax.swing.JCheckBox();
        player1jobRoller = new javax.swing.JComboBox<>();
        player1magic1 = new javax.swing.JRadioButton();
        player1magic2 = new javax.swing.JRadioButton();
        player1magic3 = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Arc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        player2clevelTickbox = new javax.swing.JCheckBox();
        player2jlevelTickbox = new javax.swing.JCheckBox();
        player2Action = new javax.swing.JComboBox<>();
        player2customjobTickbox = new javax.swing.JCheckBox();
        player2jobRoller = new javax.swing.JComboBox<>();
        player2magic1 = new javax.swing.JRadioButton();
        player2magic2 = new javax.swing.JRadioButton();
        player2magic3 = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Refia = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        player3clevelTickbox = new javax.swing.JCheckBox();
        player3jlevelTickbox = new javax.swing.JCheckBox();
        player3Action = new javax.swing.JComboBox<>();
        player3customjobTickbox = new javax.swing.JCheckBox();
        player3jobRoller = new javax.swing.JComboBox<>();
        player3magic1 = new javax.swing.JRadioButton();
        player3magic2 = new javax.swing.JRadioButton();
        player3magic3 = new javax.swing.JRadioButton();
        jSeparator4 = new javax.swing.JSeparator();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        Ingus = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        player4clevelTickbox = new javax.swing.JCheckBox();
        player4jlevelTickbox = new javax.swing.JCheckBox();
        player4Action = new javax.swing.JComboBox<>();
        player4customjobTickbox = new javax.swing.JCheckBox();
        player4jobRoller = new javax.swing.JComboBox<>();
        player4magic1 = new javax.swing.JRadioButton();
        player4magic2 = new javax.swing.JRadioButton();
        player4magic3 = new javax.swing.JRadioButton();
        jSeparator5 = new javax.swing.JSeparator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButton1 = new javax.swing.JButton();
        runButton = new javax.swing.JToggleButton();
        tab2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Auto-Battler");

        jLabel1.setText("Walking");

        leftrightTickbox.setText("Left and Right");

        updownTickbox.setText("Up and Down");
        updownTickbox.setEnabled(false);

        lrstepsRoller.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)10), Short.valueOf((short)0), Short.valueOf((short)100), Short.valueOf((short)1)));

        jLabel2.setText("L/R Steps");

        udstepsRoller.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)10), Short.valueOf((short)0), Short.valueOf((short)100), Short.valueOf((short)1)));

        jLabel3.setText("U/D Steps");

        walkingcycleRoller.setModel(new javax.swing.SpinnerNumberModel(Short.valueOf((short)10), Short.valueOf((short)0), Short.valueOf((short)100), Short.valueOf((short)1)));

        jLabel4.setText("Cycle count");

        javax.swing.GroupLayout WalkingLayout = new javax.swing.GroupLayout(Walking);
        Walking.setLayout(WalkingLayout);
        WalkingLayout.setHorizontalGroup(
            WalkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(leftrightTickbox)
            .addComponent(updownTickbox)
            .addGroup(WalkingLayout.createSequentialGroup()
                .addComponent(lrstepsRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
            .addGroup(WalkingLayout.createSequentialGroup()
                .addComponent(udstepsRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
            .addGroup(WalkingLayout.createSequentialGroup()
                .addComponent(walkingcycleRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );
        WalkingLayout.setVerticalGroup(
            WalkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WalkingLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftrightTickbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updownTickbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WalkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lrstepsRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WalkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(udstepsRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WalkingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walkingcycleRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jLabel5.setText("Battle");

        jLabel6.setText("Luneth");

        player1clevelTickbox.setText("Character level");
        player1clevelTickbox.setToolTipText("Please untick if the character is level 99");
        player1clevelTickbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1clevelTickboxActionPerformed(evt);
            }
        });

        player1jlevelTickbox.setText("Job level");

        player1Action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attack", "Job", "Guard", "Item", "Equipment", "Row" }));

        player1customjobTickbox.setText("Custom Job");

        player1jobRoller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV 1", "LV 2", "LV 3", "LV 4", "LV 5", "LV 6", "LV 7", "LV 8" }));

        player1magicGroup.add(player1magic1);
        player1magic1.setText("Entry 1");

        player1magicGroup.add(player1magic2);
        player1magic2.setText("Entry 2");

        player1magicGroup.add(player1magic3);
        player1magic3.setText("Entry 3");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout LunethLayout = new javax.swing.GroupLayout(Luneth);
        Luneth.setLayout(LunethLayout);
        LunethLayout.setHorizontalGroup(
            LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LunethLayout.createSequentialGroup()
                .addGroup(LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LunethLayout.createSequentialGroup()
                        .addComponent(player1clevelTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1jlevelTickbox))
                    .addGroup(LunethLayout.createSequentialGroup()
                        .addComponent(player1Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1customjobTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1magic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1magic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1magic3))))
        );
        LunethLayout.setVerticalGroup(
            LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LunethLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addGroup(LunethLayout.createSequentialGroup()
                .addGroup(LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1clevelTickbox)
                    .addComponent(player1jlevelTickbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LunethLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1customjobTickbox)
                    .addComponent(player1jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1magic1)
                    .addComponent(player1magic2)
                    .addComponent(player1magic3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel7.setText("Arc");

        player2clevelTickbox.setText("Character level");
        player2clevelTickbox.setToolTipText("Please untick if the character is level 99");
        player2clevelTickbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2clevelTickboxActionPerformed(evt);
            }
        });

        player2jlevelTickbox.setText("Job level");

        player2Action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attack", "Job", "Guard", "Item", "Equipment", "Row" }));

        player2customjobTickbox.setText("Custom Job");

        player2jobRoller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV 1", "LV 2", "LV 3", "LV 4", "LV 5", "LV 6", "LV 7", "LV 8" }));

        player2magicGroup.add(player2magic1);
        player2magic1.setText("Entry 1");

        player2magicGroup.add(player2magic2);
        player2magic2.setText("Entry 2");

        player2magicGroup.add(player2magic3);
        player2magic3.setText("Entry 3");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout ArcLayout = new javax.swing.GroupLayout(Arc);
        Arc.setLayout(ArcLayout);
        ArcLayout.setHorizontalGroup(
            ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArcLayout.createSequentialGroup()
                .addGroup(ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ArcLayout.createSequentialGroup()
                        .addComponent(player2clevelTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2jlevelTickbox))
                    .addGroup(ArcLayout.createSequentialGroup()
                        .addComponent(player2Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2customjobTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2magic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2magic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player2magic3))))
        );
        ArcLayout.setVerticalGroup(
            ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ArcLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addGroup(ArcLayout.createSequentialGroup()
                .addGroup(ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2clevelTickbox)
                    .addComponent(player2jlevelTickbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ArcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2customjobTickbox)
                    .addComponent(player2jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2magic1)
                    .addComponent(player2magic2)
                    .addComponent(player2magic3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setText("Refia");

        player3clevelTickbox.setText("Character level");
        player3clevelTickbox.setToolTipText("Please untick if the character is level 99");
        player3clevelTickbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3clevelTickboxActionPerformed(evt);
            }
        });

        player3jlevelTickbox.setText("Job level");
        player3jlevelTickbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player3jlevelTickboxActionPerformed(evt);
            }
        });

        player3Action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attack", "Job", "Guard", "Item", "Equipment", "Row" }));

        player3customjobTickbox.setText("Custom Job");

        player3jobRoller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV 1", "LV 2", "LV 3", "LV 4", "LV 5", "LV 6", "LV 7", "LV 8" }));

        player3magicGroup.add(player3magic1);
        player3magic1.setText("Entry 1");

        player3magicGroup.add(player3magic2);
        player3magic2.setText("Entry 2");

        player3magicGroup.add(player3magic3);
        player3magic3.setText("Entry 3");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout RefiaLayout = new javax.swing.GroupLayout(Refia);
        Refia.setLayout(RefiaLayout);
        RefiaLayout.setHorizontalGroup(
            RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefiaLayout.createSequentialGroup()
                .addGroup(RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RefiaLayout.createSequentialGroup()
                        .addComponent(player3clevelTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3jlevelTickbox))
                    .addGroup(RefiaLayout.createSequentialGroup()
                        .addComponent(player3Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3customjobTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3magic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3magic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3magic3))))
        );
        RefiaLayout.setVerticalGroup(
            RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefiaLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator4)
            .addGroup(RefiaLayout.createSequentialGroup()
                .addGroup(RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player3clevelTickbox)
                    .addComponent(player3jlevelTickbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RefiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player3Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3customjobTickbox)
                    .addComponent(player3jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3magic1)
                    .addComponent(player3magic2)
                    .addComponent(player3magic3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setText("Ingus");

        player4clevelTickbox.setText("Character level");
        player4clevelTickbox.setToolTipText("Please untick if the character is level 99");
        player4clevelTickbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player4clevelTickboxActionPerformed(evt);
            }
        });

        player4jlevelTickbox.setText("Job level");

        player4Action.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attack", "Job", "Guard", "Item", "Equipment", "Row" }));

        player4customjobTickbox.setText("Custom Job");

        player4jobRoller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV 1", "LV 2", "LV 3", "LV 4", "LV 5", "LV 6", "LV 7", "LV 8" }));

        player4magicGroup.add(player4magic1);
        player4magic1.setText("Entry 1");

        player4magicGroup.add(player4magic2);
        player4magic2.setText("Entry 2");

        player4magicGroup.add(player4magic3);
        player4magic3.setText("Entry 3");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout IngusLayout = new javax.swing.GroupLayout(Ingus);
        Ingus.setLayout(IngusLayout);
        IngusLayout.setHorizontalGroup(
            IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngusLayout.createSequentialGroup()
                .addGroup(IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngusLayout.createSequentialGroup()
                        .addComponent(player4clevelTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4jlevelTickbox))
                    .addGroup(IngusLayout.createSequentialGroup()
                        .addComponent(player4Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4customjobTickbox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4magic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4magic2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4magic3))))
        );
        IngusLayout.setVerticalGroup(
            IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngusLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator5)
            .addGroup(IngusLayout.createSequentialGroup()
                .addGroup(IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4clevelTickbox)
                    .addComponent(player4jlevelTickbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player4Action, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4customjobTickbox)
                    .addComponent(player4jobRoller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4magic1)
                    .addComponent(player4magic2)
                    .addComponent(player4magic3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BattleLayout = new javax.swing.GroupLayout(Battle);
        Battle.setLayout(BattleLayout);
        BattleLayout.setHorizontalGroup(
            BattleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addComponent(Luneth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Arc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Refia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Ingus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        BattleLayout.setVerticalGroup(
            BattleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BattleLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Luneth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Arc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ingus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        runButton.setText("better Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(Walking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(Battle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(255, 255, 255))
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(runButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(Walking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(143, 143, 143))
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Battle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(runButton)
                        .addGap(23, 23, 23))))
        );

        jTabbedPane1.addTab("Final Fantasy 3", tab1);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", tab2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player1clevelTickboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1clevelTickboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player1clevelTickboxActionPerformed

    private void player2clevelTickboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2clevelTickboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player2clevelTickboxActionPerformed

    private void player3clevelTickboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3clevelTickboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3clevelTickboxActionPerformed

    private void player4clevelTickboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player4clevelTickboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player4clevelTickboxActionPerformed

    private void player3jlevelTickboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player3jlevelTickboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_player3jlevelTickboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Battler FF3 = new Battler();
        while(true){
            System.out.println("FF3.walk(" + leftrightTickbox.isSelected() + ", " + updownTickbox.isSelected() + ", " + (short)lrstepsRoller.getValue() + ", " + (short)udstepsRoller.getValue() + ", " + (short)walkingcycleRoller.getValue() + ");");
            FF3.walk(leftrightTickbox.isSelected(), leftrightTickbox.isSelected(), (short)lrstepsRoller.getValue(), (short)udstepsRoller.getValue(), (short)walkingcycleRoller.getValue());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // TODO add your handling code here:
        Battler FF3 = new Battler();
        while(runButton.isSelected()){
            System.out.println("FF3.walk(" + leftrightTickbox.isSelected() + ", " + updownTickbox.isSelected() + ", " + (short)lrstepsRoller.getValue() + ", " + (short)udstepsRoller.getValue() + ", " + (short)walkingcycleRoller.getValue() + ");");
            //FF3.walk(leftrightTickbox.isSelected(), leftrightTickbox.isSelected(), (short)lrstepsRoller.getValue(), (short)udstepsRoller.getValue(), (short)walkingcycleRoller.getValue());
        }
    }//GEN-LAST:event_runButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Arc;
    private javax.swing.JPanel Battle;
    private javax.swing.JPanel Ingus;
    private javax.swing.JPanel Luneth;
    private javax.swing.JPanel Refia;
    private javax.swing.JPanel Walking;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox leftrightTickbox;
    private javax.swing.JSpinner lrstepsRoller;
    private javax.swing.JComboBox<String> player1Action;
    private javax.swing.JCheckBox player1clevelTickbox;
    private javax.swing.JCheckBox player1customjobTickbox;
    private javax.swing.JCheckBox player1jlevelTickbox;
    private javax.swing.JComboBox<String> player1jobRoller;
    private javax.swing.JRadioButton player1magic1;
    private javax.swing.JRadioButton player1magic2;
    private javax.swing.JRadioButton player1magic3;
    private javax.swing.ButtonGroup player1magicGroup;
    private javax.swing.JComboBox<String> player2Action;
    private javax.swing.JCheckBox player2clevelTickbox;
    private javax.swing.JCheckBox player2customjobTickbox;
    private javax.swing.JCheckBox player2jlevelTickbox;
    private javax.swing.JComboBox<String> player2jobRoller;
    private javax.swing.JRadioButton player2magic1;
    private javax.swing.JRadioButton player2magic2;
    private javax.swing.JRadioButton player2magic3;
    private javax.swing.ButtonGroup player2magicGroup;
    private javax.swing.JComboBox<String> player3Action;
    private javax.swing.JCheckBox player3clevelTickbox;
    private javax.swing.JCheckBox player3customjobTickbox;
    private javax.swing.JCheckBox player3jlevelTickbox;
    private javax.swing.JComboBox<String> player3jobRoller;
    private javax.swing.JRadioButton player3magic1;
    private javax.swing.JRadioButton player3magic2;
    private javax.swing.JRadioButton player3magic3;
    private javax.swing.ButtonGroup player3magicGroup;
    private javax.swing.JComboBox<String> player4Action;
    private javax.swing.JCheckBox player4clevelTickbox;
    private javax.swing.JCheckBox player4customjobTickbox;
    private javax.swing.JCheckBox player4jlevelTickbox;
    private javax.swing.JComboBox<String> player4jobRoller;
    private javax.swing.JRadioButton player4magic1;
    private javax.swing.JRadioButton player4magic2;
    private javax.swing.JRadioButton player4magic3;
    private javax.swing.ButtonGroup player4magicGroup;
    private javax.swing.JToggleButton runButton;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JSpinner udstepsRoller;
    private javax.swing.JCheckBox updownTickbox;
    private javax.swing.JSpinner walkingcycleRoller;
    // End of variables declaration//GEN-END:variables
}
